name: Cypress CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Start App
        run: npm run start &

      - name: Wait for App
        run: npx wait-on http://localhost:3000

      - name: Run Cypress Tests
        run: npx cypress run
